#!/bin/bash

set -e

PROJECTS="templates/service templates/native templates/qml templates/hybrid-qml templates/html5 templates/hybrid-html5 demos/cpu-hybrid-qml"

if [[ -z $(which node) ]]; then
	if [[ -z $(which apt-get) ]]; then
		echo "NodeJS not installed. Please install it manually using the procedure described here:"
		echo "   https://nodejs.org/en/download/package-manager/"
		exit 1
	fi
	echo "Installing node.js (Debian or compatible)"
	curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
	sudo apt-get install nodejs
	sudo npm install --global gulp
fi

TOPDIR=$(cd $(dirname $0) && pwd -P)
mkdir -p $TOPDIR/widgets

for project in $PROJECTS; do
	echo "====================== BUILDING PROJECT $project ============================="
	pushd $project
		if [[ -f gulpfile.js ]]; then
			[[ ! -d node_modules ]] && {
				[[ -d $TOPDIR/node_modules ]] && ln -sf $TOPDIR/node_modules . || {
					npm install
					mv node_modules bower_components $TOPDIR
					ln -sf $TOPDIR/node_modules .
					ln -sf $TOPDIR/bower_components .
				}
			}
			[[ ! -d bower_components ]] && {
				[[ -d $TOPDIR/bower_components ]] && ln -sf $TOPDIR/bower_components || { echo "Bower components not found in $TOPDIR"; exit 1; }
			}
		fi

		mkdir -p build
		pushd build
			cmake ..
			make
			cp -v *.wgt $TOPDIR/widgets/
		popd
	popd
done

echo "============================= BUILD FINISHED ================================="
echo "Available widgets:"
ls -l $TOPDIR/widgets

echo "To deploy: "
echo "# BOARDIP=1.2.3.4"
echo "# scp *.wgt root@\$BOARDIP:~/"
echo "# ssh root@\$BOARDIP"
echo "# for w in i\$(ls *.wgt); do afm-util install \$w; done"
echo "# afm-util list"
